# Generated by Django 3.0.3 on 2020-05-07 21:44

from django.db import migrations

GROUPS = [
    {
        'name': 'admin',
    },
    {
        'name': 'worker',
    },
    {
        'name': 'user',
    },
]


def add_group_data(apps, schema_editor):
    group_model_class = apps.get_model('auth', 'Group')
    for group in GROUPS:
        group_object = group_model_class.objects.create(
            name=group['name'],
        )


def remove_group_data(apps, schema_editor):
    group_model_class = apps.get_model('auth', 'Group')
    for group in GROUPS:
        group_object = group_model_class.objects.get(
            name=group['name']
        )
        group_object.delete()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(
            add_group_data,
            remove_group_data
        )
    ]
