# Generated by Django 3.0.3 on 2020-05-07 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_id', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=45, unique=True)),
                ('location', models.CharField(max_length=80, unique=True)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=80)),
                ('eventDate', models.DateField()),
                ('eventTime', models.CharField(max_length=20)),
                ('registeredTime', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('found', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registeredTime'],
            },
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=80)),
                ('eventDate', models.DateField()),
                ('eventTime', models.CharField(max_length=20)),
                ('registeredTime', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('picked', models.BooleanField(default=False)),
                ('pickedBy', models.CharField(blank=True, default='', max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pickedTime', models.DateTimeField(blank=True, null=True)),
                ('pickedInfo', models.CharField(blank=True, default='', max_length=80)),
                ('admin', models.CharField(blank=True, default='', max_length=30)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='info.Site')),
            ],
            options={
                'ordering': ['registeredTime'],
            },
        ),
    ]
