# Generated by Django 3.0.3 on 2020-03-20 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ps',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='registeredTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 18, 28, 31, 213623, tzinfo=utc)),
        ),
    ]
