# Generated by Django 3.0.3 on 2020-05-14 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_advice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='eventDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='eventDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
