# Generated by Django 3.0.3 on 2020-03-20 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20200320_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='registeredTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 18, 31, 5, 881661, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
