# Generated by Django 3.0.3 on 2020-05-14 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_advice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='eventDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='eventDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
