# Generated by Django 3.0.3 on 2020-05-19 01:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_set_dafault_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
