# Generated by Django 3.0.3 on 2020-06-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_site_contact_type_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='image',
            field=models.ImageField(blank=True, upload_to='found_item_img'),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='lost_item_img'),
        ),
    ]
