# Generated by Django 3.0.3 on 2020-03-20 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20200320_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='registeredTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 18, 40, 13, 550173, tzinfo=utc)),
        ),
    ]
