# Generated by Django 3.0.3 on 2020-03-20 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_auto_20200320_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='registeredTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
