# Generated by Django 3.0.3 on 2020-03-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20200320_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('L', 'Lost'), ('F', 'Found')], default='L', max_length=10),
        ),
    ]
