# Generated by Django 3.0.3 on 2020-03-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('L', 'Lost'), ('F', 'Found')], max_length=10),
        ),
    ]
