# Generated by Django 3.0.3 on 2020-03-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20200320_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['registeredTime']},
        ),
    ]
