# Generated by Django 3.0.3 on 2020-05-04 15:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_load_site_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=80)),
                ('eventDate', models.DateField()),
                ('eventTime', models.CharField(max_length=20)),
                ('registeredTime', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('userContact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('picked', models.BooleanField(default=False)),
                ('pickedTime', models.DateTimeField(blank=True)),
                ('pickedInfo', models.CharField(blank=True, default='', max_length=80)),
                ('admin', models.CharField(blank=True, default='', max_length=30)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='info.Site')),
            ],
            options={
                'ordering': ['registeredTime'],
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=80)),
                ('eventDate', models.DateField()),
                ('eventTime', models.CharField(max_length=20)),
                ('registeredTime', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=80, null=True)),
                ('userContact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('found', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='info.User')),
            ],
            options={
                'ordering': ['registeredTime'],
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
