# Generated by Django 3.0.3 on 2020-05-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_auto_20200504_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lostitem',
            old_name='userContact',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='lostitem',
            name='email',
            field=models.EmailField(default='7271@qq.com', max_length=254),
            preserve_default=False,
        ),
    ]
