# Generated by Django 3.0.3 on 2020-05-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_auto_20200504_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founditem',
            old_name='userContact',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='founditem',
            name='email',
            field=models.EmailField(default='321@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='founditem',
            name='pickedBy',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
