# Generated by Django 3.0.3 on 2020-05-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_auto_add_pick_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
